# Generated by Django 5.0.3 on 2026-03-19 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('profile_photo_url', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('worker', 'Worker'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned'), ('pending_verification', 'Pending Verification')], default='active', max_length=30)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('otp_secret', models.TextField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_address', models.TextField(blank=True, null=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('is_repeat_customer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, help_text='Base rate in PKR per hour', max_digits=10)),
                ('service_radius_km', models.DecimalField(decimal_places=1, default=10.0, max_digits=5)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('cnic_front_url', models.TextField(blank=True, null=True)),
                ('cnic_back_url', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_jobs_completed', models.PositiveIntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worker_profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkerService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('carpenter', 'Carpenter'), ('mechanic', 'Mechanic')], max_length=20)),
                ('price_modifier_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('worker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.workerprofile')),
            ],
            options={
                'db_table': 'worker_services',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['verification_status'], name='worker_prof_verific_9a110a_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['is_available'], name='worker_prof_is_avai_07874f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workerservice',
            unique_together={('worker_profile', 'category')},
        ),
    ]
