# Generated by Django 6.0.4 on 2026-05-04 13:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tool_workertool_portfolio_favorite_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerportfoliophoto',
            options={'ordering': ['order', 'uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo_url',
        ),
        migrations.RemoveField(
            model_name='workerportfoliophoto',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='cnic_back_url',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='cnic_front_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_photo_path),
        ),
        migrations.AddField(
            model_name='workerportfoliophoto',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerportfoliophoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.portfolio_photo_path),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.cnic_back_path),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.cnic_front_path),
        ),
    ]
